ame: Fed Rate Alert Daily

on:
  schedule:
    # Runs every day at 14:00 UTC (adjust time as needed)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-fed-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fed_alert.py script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: python fed_alert.py
